insert into sector (code, name, level, parent_code) values ('MANUFACTURING', 'Manufacturing', 1, NULL);
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_CONSTRUCTION_MATERIALS', 'Construction materials', 2, 'MANUFACTURING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_ELECTRONICS_AND_OPTICS', 'Electronics and Optics', 2, 'MANUFACTURING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FOOD_AND_BEVERAGE', 'Food and Beverage', 2, 'MANUFACTURING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FOOD_AND_BEVERAGE_BAKERY_CONFECTIONERY_PRODUCTS', 'Bakery & confectionery products', 3, 'MANUFACTURING_FOOD_AND_BEVERAGE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FOOD_AND_BEVERAGE_BEVERAGES', 'Beverages', 3, 'MANUFACTURING_FOOD_AND_BEVERAGE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FOOD_AND_BEVERAGE_FISH_FISH_PRODUCTS', 'Fish & fish products ', 3, 'MANUFACTURING_FOOD_AND_BEVERAGE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FOOD_AND_BEVERAGE_MEAT_MEAT_PRODUCTS', 'Meat & meat products', 3, 'MANUFACTURING_FOOD_AND_BEVERAGE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FOOD_AND_BEVERAGE_MILK_DAIRY_PRODUCTS', 'Milk & dairy products ', 3, 'MANUFACTURING_FOOD_AND_BEVERAGE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FOOD_AND_BEVERAGE_OTHER', 'Other', 3, 'MANUFACTURING_FOOD_AND_BEVERAGE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FOOD_AND_BEVERAGE_SWEETS_SNACK_FOOD', 'Sweets & snack food', 3, 'MANUFACTURING_FOOD_AND_BEVERAGE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FURNITURE', 'Furniture', 2, 'MANUFACTURING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FURNITURE_BATHROOM_SAUNA', 'Bathroom/sauna ', 3, 'MANUFACTURING_FURNITURE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FURNITURE_BEDROOM', 'Bedroom', 3, 'MANUFACTURING_FURNITURE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FURNITURE_CHILDRENS_ROOM', 'Children’s room ', 3, 'MANUFACTURING_FURNITURE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FURNITURE_KITCHEN', 'Kitchen ', 3, 'MANUFACTURING_FURNITURE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FURNITURE_LIVING_ROOM', 'Living room ', 3, 'MANUFACTURING_FURNITURE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FURNITURE_OFFICE', 'Office', 3, 'MANUFACTURING_FURNITURE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FURNITURE_OTHER_FURNITURE', 'Other (Furniture)', 3, 'MANUFACTURING_FURNITURE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FURNITURE_OUTDOOR', 'Outdoor ', 3, 'MANUFACTURING_FURNITURE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_FURNITURE_PROJECT_FURNITURE', 'Project furniture', 3, 'MANUFACTURING_FURNITURE');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_MACHINERY', 'Machinery', 2, 'MANUFACTURING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_MACHINERY_MACHINERY_COMPONENTS', 'Machinery components', 3, 'MANUFACTURING_MACHINERY');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_MACHINERY_MACHINERY_EQUIPMENT_TOOLS', 'Machinery equipment/tools', 3, 'MANUFACTURING_MACHINERY');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_MACHINERY_MANUFACTURE_OF_MACHINERY', 'Manufacture of machinery ', 3, 'MANUFACTURING_MACHINERY');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_MACHINERY_MARITIME', 'Maritime', 3, 'MANUFACTURING_MACHINERY');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_MACHINERY_MARITIME_ALUMINIUM_AND_STEEL_WORKBOATS', 'Aluminium and steel workboats ', 4, 'MANUFACTURING_MACHINERY_MARITIME');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_MACHINERY_MARITIME_BOAT_YACHT_BUILDING', 'Boat/Yacht building', 4, 'MANUFACTURING_MACHINERY_MARITIME');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_MACHINERY_MARITIME_SHIP_REPAIR_AND_CONVERSION', 'Ship repair and conversion', 4, 'MANUFACTURING_MACHINERY_MARITIME');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_MACHINERY_METAL_STRUCTURES', 'Metal structures', 3, 'MANUFACTURING_MACHINERY');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_MACHINERY_OTHER', 'Other', 3, 'MANUFACTURING_MACHINERY');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_MACHINERY_REPAIR_AND_MAINTENANCE_SERVICE', 'Repair and maintenance service', 3, 'MANUFACTURING_MACHINERY');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_METALWORKING', 'Metalworking', 2, 'MANUFACTURING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_METALWORKING_CONSTRUCTION_OF_METAL_STRUCTURES', 'Construction of metal structures', 3, 'MANUFACTURING_METALWORKING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_METALWORKING_HOUSES_AND_BUILDINGS', 'Houses and buildings', 3, 'MANUFACTURING_METALWORKING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_METALWORKING_METAL_PRODUCTS', 'Metal products', 3, 'MANUFACTURING_METALWORKING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_METALWORKING_METAL_WORKS', 'Metal works', 3, 'MANUFACTURING_METALWORKING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_METALWORKING_METAL_WORKS_CNC_MACHINING', 'CNC-machining', 4, 'MANUFACTURING_METALWORKING_METAL_WORKS');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_METALWORKING_METAL_WORKS_FORGINGS_FASTENERS', 'Forgings, Fasteners ', 4, 'MANUFACTURING_METALWORKING_METAL_WORKS');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_METALWORKING_METAL_WORKS_GAS_PLASMA_LASER_CUTTING', 'Gas, Plasma, Laser cutting', 4, 'MANUFACTURING_METALWORKING_METAL_WORKS');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_METALWORKING_METAL_WORKS_MIG_TIG_ALUMINUM_WELDING', 'MIG, TIG, Aluminum welding', 4, 'MANUFACTURING_METALWORKING_METAL_WORKS');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_PLASTIC_AND_RUBBER', 'Plastic and Rubber', 2, 'MANUFACTURING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_PLASTIC_AND_RUBBER_PACKAGING', 'Packaging', 3, 'MANUFACTURING_PLASTIC_AND_RUBBER');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_PLASTIC_AND_RUBBER_PLASTIC_GOODS', 'Plastic goods', 3, 'MANUFACTURING_PLASTIC_AND_RUBBER');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_PLASTIC_AND_RUBBER_PLASTIC_PROCESSING_TECHNOLOGY', 'Plastic processing technology', 3, 'MANUFACTURING_PLASTIC_AND_RUBBER');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_PLASTIC_AND_RUBBER_PLASTIC_PROCESSING_TECHNOLOGY_BLOWING', 'Blowing', 4, 'MANUFACTURING_PLASTIC_AND_RUBBER_PLASTIC_PROCESSING_TECHNOLOGY');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_PLASTIC_AND_RUBBER_PLASTIC_PROCESSING_TECHNOLOGY_MOULDING', 'Moulding', 4, 'MANUFACTURING_PLASTIC_AND_RUBBER_PLASTIC_PROCESSING_TECHNOLOGY');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_PLASTIC_AND_RUBBER_PLASTIC_PROCESSING_TECHNOLOGY_PLASTICS_WELDING_AND_PROCESSING', 'Plastics welding and processing', 4, 'MANUFACTURING_PLASTIC_AND_RUBBER_PLASTIC_PROCESSING_TECHNOLOGY');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_PLASTIC_AND_RUBBER_PLASTIC_PROFILES', 'Plastic profiles', 3, 'MANUFACTURING_PLASTIC_AND_RUBBER');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_PRINTING', 'Printing ', 2, 'MANUFACTURING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_PRINTING_ADVERTISING', 'Advertising', 3, 'MANUFACTURING_PRINTING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_PRINTING_BOOK_PERIODICALS_PRINTING', 'Book/Periodicals printing', 3, 'MANUFACTURING_PRINTING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_PRINTING_LABELLING_AND_PACKAGING_PRINTING', 'Labelling and packaging printing', 3, 'MANUFACTURING_PRINTING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_TEXTILE_AND_CLOTHING', 'Textile and Clothing', 2, 'MANUFACTURING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_TEXTILE_AND_CLOTHING_CLOTHING', 'Clothing', 3, 'MANUFACTURING_TEXTILE_AND_CLOTHING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_TEXTILE_AND_CLOTHING_TEXTILE', 'Textile', 3, 'MANUFACTURING_TEXTILE_AND_CLOTHING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_WOOD', 'Wood', 2, 'MANUFACTURING');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_WOOD_OTHER_WOOD', 'Other (Wood)', 3, 'MANUFACTURING_WOOD');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_WOOD_WOODEN_BUILDING_MATERIALS', 'Wooden building materials', 3, 'MANUFACTURING_WOOD');
insert into sector (code, name, level, parent_code) values ('MANUFACTURING_WOOD_WOODEN_HOUSES', 'Wooden houses', 3, 'MANUFACTURING_WOOD');
insert into sector (code, name, level, parent_code) values ('OTHER', 'Other', 1, NULL);
insert into sector (code, name, level, parent_code) values ('OTHER_CREATIVE_INDUSTRIES', 'Creative industries', 2, 'OTHER');
insert into sector (code, name, level, parent_code) values ('OTHER_ENERGY_TECHNOLOGY', 'Energy technology', 2, 'OTHER');
insert into sector (code, name, level, parent_code) values ('OTHER_ENVIRONMENT', 'Environment', 2, 'OTHER');
insert into sector (code, name, level, parent_code) values ('SERVICE', 'Service', 1, NULL);
insert into sector (code, name, level, parent_code) values ('SERVICE_BUSINESS_SERVICES', 'Business services', 2, 'SERVICE');
insert into sector (code, name, level, parent_code) values ('SERVICE_ENGINEERING', 'Engineering', 2, 'SERVICE');
insert into sector (code, name, level, parent_code) values ('SERVICE_INFORMATION_TECHNOLOGY_AND_TELECOMMUNICATIONS', 'Information Technology and Telecommunications', 2, 'SERVICE');
insert into sector (code, name, level, parent_code) values ('SERVICE_INFORMATION_TECHNOLOGY_AND_TELECOMMUNICATIONS_DATA_PROCESSING_WEB_PORTALS_E_MARKETING', 'Data processing, Web portals, E-marketing', 3, 'SERVICE_INFORMATION_TECHNOLOGY_AND_TELECOMMUNICATIONS');
insert into sector (code, name, level, parent_code) values ('SERVICE_INFORMATION_TECHNOLOGY_AND_TELECOMMUNICATIONS_PROGRAMMING_CONSULTANCY', 'Programming, Consultancy', 3, 'SERVICE_INFORMATION_TECHNOLOGY_AND_TELECOMMUNICATIONS');
insert into sector (code, name, level, parent_code) values ('SERVICE_INFORMATION_TECHNOLOGY_AND_TELECOMMUNICATIONS_SOFTWARE_HARDWARE', 'Software, Hardware', 3, 'SERVICE_INFORMATION_TECHNOLOGY_AND_TELECOMMUNICATIONS');
insert into sector (code, name, level, parent_code) values ('SERVICE_INFORMATION_TECHNOLOGY_AND_TELECOMMUNICATIONS_TELECOMMUNICATIONS', 'Telecommunications', 3, 'SERVICE_INFORMATION_TECHNOLOGY_AND_TELECOMMUNICATIONS');
insert into sector (code, name, level, parent_code) values ('SERVICE_TOURISM', 'Tourism', 2, 'SERVICE');
insert into sector (code, name, level, parent_code) values ('SERVICE_TRANSLATION_SERVICES', 'Translation services', 2, 'SERVICE');
insert into sector (code, name, level, parent_code) values ('SERVICE_TRANSPORT_AND_LOGISTICS', 'Transport and Logistics', 2, 'SERVICE');
insert into sector (code, name, level, parent_code) values ('SERVICE_TRANSPORT_AND_LOGISTICS_AIR', 'Air', 3, 'SERVICE_TRANSPORT_AND_LOGISTICS');
insert into sector (code, name, level, parent_code) values ('SERVICE_TRANSPORT_AND_LOGISTICS_RAIL', 'Rail', 3, 'SERVICE_TRANSPORT_AND_LOGISTICS');
insert into sector (code, name, level, parent_code) values ('SERVICE_TRANSPORT_AND_LOGISTICS_ROAD', 'Road', 3, 'SERVICE_TRANSPORT_AND_LOGISTICS');
insert into sector (code, name, level, parent_code) values ('SERVICE_TRANSPORT_AND_LOGISTICS_WATER', 'Water', 3, 'SERVICE_TRANSPORT_AND_LOGISTICS');
