spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sector
    username: sector-api
    password: sector-api
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true